using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using SharpSFV.Models;
using SharpSFV.Interop;

namespace SharpSFV
{
    public partial class Form1
    {
        private CheckBox? _chkComments; // Field for Comments Toggle

        private void SetupLayout()
        {
            // 1. Ensure all components are initialized
            if (_mainSplitter == null || lvFiles == null) SetupActiveJobsPanel();
            if (_menuStrip == null) SetupCustomMenu();
            if (_statsPanel == null) SetupStatsPanel();
            if (_filterPanel == null) SetupFilterPanel();
            if (_advancedPanel == null) SetupAdvancedPanel();
            if (_commentsPanel == null) SetupCommentsPanel();

            this.Controls.Clear();
            this.MinimumSize = new Size(600, 400);

            // 2. Configure Components
            Panel progressPanel = new Panel { Height = 25, Dock = DockStyle.Bottom, Padding = new Padding(2) };

            if (progressBarTotal != null)
            {
                progressBarTotal.Dock = DockStyle.Fill;
                progressPanel.Controls.Add(progressBarTotal);
            }

            if (lvFiles != null)
            {
                lvFiles.Dock = DockStyle.Fill;
                lvFiles.Scrollable = true;
            }

            if (_mainSplitter != null)
            {
                _mainSplitter.Dock = DockStyle.Fill;
                if (lvFiles != null && !_mainSplitter.Panel2.Controls.Contains(lvFiles))
                {
                    _mainSplitter.Panel2.Controls.Add(lvFiles);
                }
            }

            // 3. Add Controls (Z-Order: Fill First, Top Last)
            if (_mainSplitter != null) this.Controls.Add(_mainSplitter);
            else if (lvFiles != null) this.Controls.Add(lvFiles);

            this.Controls.Add(progressPanel);

            if (_filterPanel != null) this.Controls.Add(_filterPanel);
            if (_advancedPanel != null) this.Controls.Add(_advancedPanel);
            if (_commentsPanel != null) this.Controls.Add(_commentsPanel);
            if (_statsPanel != null) this.Controls.Add(_statsPanel);
            if (_menuStrip != null) this.Controls.Add(_menuStrip);
        }

        private void SetupAdvancedPanel()
        {
            if (_advancedPanel != null) return;

            _advancedPanel = new Panel
            {
                Height = 35,
                Dock = DockStyle.Top,
                BackColor = Color.FromArgb(240, 240, 245),
                Padding = new Padding(2),
                Visible = _settings.ShowAdvancedBar
            };

            ToolTip tt = new ToolTip
            {
                AutoPopDelay = 15000,
                InitialDelay = 500,
                ReshowDelay = 500,
                ShowAlways = true,
                IsBalloon = false
            };

            Label lblPrefix = new Label { Text = "Path Prefix:", AutoSize = true, Location = new Point(5, 10) };
            _txtPathPrefix = new TextBox { Width = 150, Location = new Point(75, 7), Text = _settings.PathPrefix };
            tt.SetToolTip(_txtPathPrefix, "Virtual folder structure to prepend to saved paths.\nExample: incoming\\iso\\");
            _txtPathPrefix.TextChanged += (s, e) => _settings.PathPrefix = _txtPathPrefix.Text;

            Label lblInc = new Label { Text = "Include:", AutoSize = true, Location = new Point(240, 10) };
            _txtInclude = new TextBox { Width = 80, Location = new Point(290, 7), Text = _settings.IncludePattern };
            tt.SetToolTip(_txtInclude, "Only process files matching these patterns.\nSeparate multiple patterns with a semicolon (;).\nExample: *.iso;*.mkv;*.rar");
            _txtInclude.TextChanged += (s, e) => _settings.IncludePattern = _txtInclude.Text;

            Label lblExc = new Label { Text = "Exclude:", AutoSize = true, Location = new Point(380, 10) };
            _txtExclude = new TextBox { Width = 80, Location = new Point(430, 7), Text = _settings.ExcludePattern };
            tt.SetToolTip(_txtExclude, "Skip files matching these patterns.\nSeparate multiple patterns with a semicolon (;).\nExample: *.txt;*.nfo;*.sfv");
            _txtExclude.TextChanged += (s, e) => _settings.ExcludePattern = _txtExclude.Text;

            _chkRecursive = new CheckBox { Text = "Scan Subfolders", AutoSize = true, Location = new Point(530, 9), Checked = _settings.ScanRecursive };
            tt.SetToolTip(_chkRecursive, "If checked, all subdirectories will be scanned recursively.");
            _chkRecursive.CheckedChanged += (s, e) => _settings.ScanRecursive = _chkRecursive.Checked;

            _chkComments = new CheckBox { Text = "Save Comments", AutoSize = true, Location = new Point(650, 9), Checked = _settings.EnableChecksumComments };
            tt.SetToolTip(_chkComments, "If checked, header comments (Generated By / Algorithm) will be written to the output file.");
            _chkComments.CheckedChanged += (s, e) => _settings.EnableChecksumComments = _chkComments.Checked;

            _advancedPanel.Controls.AddRange(new Control[] {
                lblPrefix, _txtPathPrefix,
                lblInc, _txtInclude,
                lblExc, _txtExclude,
                _chkRecursive,
                _chkComments
            });
        }

        private void SetupCommentsPanel()
        {
            if (_commentsPanel != null) return;

            _commentsPanel = new Panel
            {
                Height = 60,
                Dock = DockStyle.Top,
                BackColor = SystemColors.Info,
                Padding = new Padding(5),
                Visible = false
            };

            _txtComments = new TextBox
            {
                Multiline = true,
                ReadOnly = true,
                ScrollBars = ScrollBars.Vertical,
                Dock = DockStyle.Fill,
                BorderStyle = BorderStyle.None,
                BackColor = SystemColors.Info,
                ForeColor = SystemColors.InfoText,
                Font = new Font("Consolas", 9F, FontStyle.Regular),
                Text = ""
            };

            _commentsPanel.Controls.Add(_txtComments);
        }

        private void SetupStatsPanel()
        {
            if (_statsPanel != null) return;

            _statsPanel = new Panel { Height = 50, Dock = DockStyle.Top, BackColor = SystemColors.ControlLight, Padding = new Padding(10, 5, 10, 5) };

            _lblProgress = new Label { Text = "Ready", AutoSize = true, Location = new Point(10, 8) };
            _lblProgress.Font = _fontBold;

            _lblTotalTime = new Label
            {
                Text = "",
                AutoSize = true,
                Location = new Point(300, 8),
                ForeColor = Color.Blue,
                Font = _fontBold,
                Visible = _settings.ShowTimeTab
            };

            _statsFlowPanel = new FlowLayoutPanel
            {
                Location = new Point(10, 28),
                Size = new Size(600, 20),
                AutoSize = true,
                FlowDirection = FlowDirection.LeftToRight,
                Padding = new Padding(0),
                WrapContents = false
            };

            _lblStatsOK = new Label { Text = "OK: 0", AutoSize = true, ForeColor = Color.DarkGreen, Font = new Font(this.Font, FontStyle.Bold), Margin = new Padding(0, 0, 15, 0) };
            _lblStatsBad = new Label { Text = "BAD: 0", AutoSize = true, ForeColor = Color.Red, Font = new Font(this.Font, FontStyle.Bold), Margin = new Padding(0, 0, 15, 0) };
            _lblStatsMissing = new Label { Text = "MISSING: 0", AutoSize = true, ForeColor = Color.DarkGoldenrod, Font = new Font(this.Font, FontStyle.Bold), Margin = new Padding(0, 0, 0, 0) };

            _statsFlowPanel.Controls.Add(_lblStatsOK);
            _statsFlowPanel.Controls.Add(_lblStatsBad);
            _statsFlowPanel.Controls.Add(_lblStatsMissing);

            int btnWidth = 75;
            int btnHeight = 26;
            int margin = 10;
            int xStop = _statsPanel.ClientSize.Width - btnWidth - margin;
            int xPause = xStop - btnWidth - margin;

            _btnStop = new Button
            {
                Text = "Stop",
                Location = new Point(xStop, 10),
                Size = new Size(btnWidth, btnHeight),
                ForeColor = Color.Red,
                Enabled = false,
                Anchor = AnchorStyles.Right | AnchorStyles.Top,
                UseVisualStyleBackColor = true
            };
            _btnStop.Click += (s, e) => PerformCancelAction();

            _btnPause = new Button
            {
                Text = "Pause",
                Location = new Point(xPause, 10),
                Size = new Size(btnWidth, btnHeight),
                ForeColor = SystemColors.ControlText,
                Enabled = false,
                Anchor = AnchorStyles.Right | AnchorStyles.Top,
                UseVisualStyleBackColor = true
            };
            _btnPause.Click += (s, e) => PerformTogglePause();

            _statsPanel.Controls.Add(_lblProgress);
            _statsPanel.Controls.Add(_lblTotalTime);
            _statsPanel.Controls.Add(_statsFlowPanel);

            _statsPanel.Controls.Add(_btnPause);
            _statsPanel.Controls.Add(_btnStop);

            _btnPause.BringToFront();
            _btnStop.BringToFront();
        }

        private void SetupFilterPanel()
        {
            if (_filterPanel != null) return;

            _filterPanel = new Panel { Height = 35, Dock = DockStyle.Top, BackColor = SystemColors.Control, Padding = new Padding(5), Visible = false };

            Label lblSearch = new Label { Text = "Search:", AutoSize = true, Location = new Point(10, 8) };
            _txtFilter = new TextBox { Width = 200, Location = new Point(60, 5) };

            _txtFilter.TextChanged += (s, e) => { _filterDebounceTimer?.Change(300, System.Threading.Timeout.Infinite); };

            Label lblStatus = new Label { Text = "Status:", AutoSize = true, Location = new Point(280, 8) };
            _cmbStatusFilter = new ComboBox { Width = 100, Location = new Point(330, 5), DropDownStyle = ComboBoxStyle.DropDownList };
            _cmbStatusFilter.Items.AddRange(new object[] { "All", "Pending", "OK", "BAD", "MISSING", "Waiting..." });
            _cmbStatusFilter.SelectedIndex = 0;
            _cmbStatusFilter.SelectedIndexChanged += (s, e) => ApplyFilter();

            _chkShowDuplicates = new CheckBox { Text = "Show Duplicates", AutoSize = true, Location = new Point(450, 8) };
            _chkShowDuplicates.CheckedChanged += (s, e) => ApplyFilter();

            _filterPanel.Controls.AddRange(new Control[] { lblSearch, _txtFilter, lblStatus, _cmbStatusFilter, _chkShowDuplicates });

            _filterDebounceTimer = new System.Threading.Timer(OnFilterDebounce, null, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
        }

        private void SetupUIForMode(string mode)
        {
            if (lvFiles == null) return;

            lvFiles.ColumnWidthChanging -= LvFiles_ColumnWidthChanging;
            lvFiles.Columns.Clear();
            _originalColWidths.Clear();
            _listSorter.SortColumn = -1;
            _listSorter.Order = SortOrder.None;

            _isVerificationMode = (mode == "Verification");

            lvFiles.AllowColumnReorder = !_settings.LockColumns;

            void AddColLocal(string text, int width, string tag)
            {
                ColumnHeader ch = lvFiles.Columns.Add(text, width);
                ch.Tag = tag;
                _originalColWidths[ch.Index] = width;
            }

            AddColLocal("File Name", 300, "Name");

            if (_settings.ShowHashCol)
                AddColLocal("Hash", 220, "Hash");

            AddColLocal("Status", 100, "Status");

            if (_isVerificationMode && _settings.ShowExpectedHashCol)
                AddColLocal("Expected Hash", 220, "Expected");

            if (_settings.ShowTimeTab)
                AddColLocal("Time", 80, "Time");

            if (_lblTotalTime != null)
                _lblTotalTime.Visible = _settings.ShowTimeTab;

            // TITLE BAR LOGIC:
            // Standard Mode (Idle) -> "SharpSFV"
            // Verification Mode -> "SharpSFV - Verify"
            // Job Mode handled by SetAppMode
            if (!_isJobMode)
            {
                this.Text = (_isVerificationMode) ? "SharpSFV - Verify" : "SharpSFV";
            }

            if (_settings.ColumnOrder.Count > 0)
            {
                foreach (ColumnHeader ch in lvFiles.Columns)
                {
                    if (ch.Tag is string tag && _settings.ColumnOrder.TryGetValue(tag, out int displayIdx))
                    {
                        if (displayIdx < lvFiles.Columns.Count) ch.DisplayIndex = displayIdx;
                    }
                }
            }

            lvFiles.ColumnWidthChanging += LvFiles_ColumnWidthChanging;
        }

        private void SetAppMode(bool jobMode)
        {
            if (_isJobMode == jobMode) return;
            _isJobMode = jobMode;

            if (_menuJobsEnable != null) _menuJobsEnable.Checked = _isJobMode;

            lvFiles.BeginUpdate();
            lvFiles.Columns.Clear();
            _originalColWidths.Clear();

            if (_isJobMode)
            {
                AddCol("Job Name", 250, "JobName");
                AddCol("Root Path", 350, "RootPath");
                AddCol("Progress", 100, "Progress");
                AddCol("Status", 100, "Status");

                if (_mainSplitter != null) _mainSplitter.Panel1Collapsed = true;
                if (_filterPanel != null) _filterPanel.Visible = false;
                if (_advancedPanel != null) _advancedPanel.Visible = false;
                if (_commentsPanel != null) _commentsPanel.Visible = false;

                lvFiles.VirtualListSize = _jobStore.Count;
                this.Text = $"SharpSFV - Job Queue [{_currentHashType}]";

                UpdateJobStats();
            }
            else
            {
                SetupUIForMode("Creation");
                if (_settings.ShowFilterPanel && _filterPanel != null) _filterPanel.Visible = true;
                if (_settings.ShowAdvancedBar && _advancedPanel != null) _advancedPanel.Visible = true;

                if (_commentsPanel != null && _txtComments != null)
                    _commentsPanel.Visible = !string.IsNullOrWhiteSpace(_txtComments.Text);

                lvFiles.VirtualListSize = _displayIndices.Count;
                SetAlgorithm(_currentHashType); // Restore standard selection visual

                UpdateStats(0, 0, 0, 0, 0);
            }

            lvFiles.EndUpdate();
            lvFiles.Invalidate();
        }

        private void UpdateStats(int current, int total, int ok, int bad, int missing)
        {
            if (_isJobMode) return;

            if (_lblProgress != null)
            {
                if (total == 0 && current == 0) _lblProgress.Text = "Ready";
                else _lblProgress.Text = $"Completed files: {current} / {total}";
                _lblProgress.Update();
            }

            if (_lblStatsOK != null)
            {
                _lblStatsOK.Text = $"OK: {ok}";
                _lblStatsOK.ForeColor = ColGreenText;
            }
            if (_lblStatsBad != null)
            {
                _lblStatsBad.Text = $"BAD: {bad}";
                _lblStatsBad.ForeColor = ColRedText;
            }
            if (_lblStatsMissing != null)
            {
                _lblStatsMissing.Text = $"MISSING: {missing}";
                _lblStatsMissing.ForeColor = ColYellowText;
            }

            if (_menuGenBadFiles != null)
                _menuGenBadFiles.Enabled = (bad > 0);

            _statsFlowPanel?.Update();
        }

        private void UpdateJobStats()
        {
            if (!_isJobMode) return;

            int done = 0;
            int error = 0;
            int inProgress = 0;
            int paused = 0;

            for (int i = 0; i < _jobStore.Count; i++)
            {
                switch (_jobStore.Statuses[i])
                {
                    case JobStatus.Done: done++; break;
                    case JobStatus.Error: error++; break;
                    case JobStatus.InProgress: inProgress++; break;
                    case JobStatus.Paused: paused++; break;
                }
            }

            if (_lblProgress != null) _lblProgress.Text = $"Jobs Completed: {done} / {_jobStore.Count}";

            if (_lblStatsOK != null)
            {
                _lblStatsOK.Text = $"DONE: {done}";
                _lblStatsOK.ForeColor = ColGreenText;
            }

            if (_lblStatsBad != null)
            {
                _lblStatsBad.Text = $"ERROR: {error}";
                _lblStatsBad.ForeColor = ColRedText;
            }

            if (_lblStatsMissing != null)
            {
                _lblStatsMissing.Text = $"ACTIVE: {inProgress + paused}";
                _lblStatsMissing.ForeColor = Color.Blue;
            }
        }

        private void ApplySettings()
        {
            if (_settings.WindowSize.Width > 100) this.Size = _settings.WindowSize;

            if (_settings.HasCustomLocation)
            {
                this.StartPosition = FormStartPosition.Manual;
                this.Location = _settings.WindowLocation;
                bool isOnScreen = Screen.AllScreens.Any(s => s.WorkingArea.IntersectsWith(this.Bounds));
                if (!isOnScreen) this.StartPosition = FormStartPosition.CenterScreen;
            }

            if (_menuViewTime != null) _menuViewTime.Checked = _settings.ShowTimeTab;
            if (_menuViewShowFullPaths != null) _menuViewShowFullPaths.Checked = _settings.ShowFullPaths;

            if (_menuOptionsFilter != null) _menuOptionsFilter.Checked = _settings.ShowFilterPanel;

            if (_menuOptionsAdvanced != null) _menuOptionsAdvanced.Checked = _settings.ShowAdvancedBar;
            if (_advancedPanel != null) _advancedPanel.Visible = _settings.ShowAdvancedBar;

            // Apply Advanced Controls
            if (_txtPathPrefix != null) _txtPathPrefix.Text = _settings.PathPrefix;
            if (_txtInclude != null) _txtInclude.Text = _settings.IncludePattern;
            if (_txtExclude != null) _txtExclude.Text = _settings.ExcludePattern;
            if (_chkRecursive != null) _chkRecursive.Checked = _settings.ScanRecursive;
            if (_chkComments != null) _chkComments.Checked = _settings.EnableChecksumComments;

            SetProcessingMode(_settings.ProcessingMode);
            SetPathStorageMode(_settings.PathStorageMode);

            if (_menuViewHash != null) _menuViewHash.Checked = _settings.ShowHashCol;
            if (_menuViewExpected != null) _menuViewExpected.Checked = _settings.ShowExpectedHashCol;
            if (_menuViewLockCols != null) _menuViewLockCols.Checked = _settings.LockColumns;

            if (_filterPanel != null) _filterPanel.Visible = _settings.ShowFilterPanel;

            ToggleTimeColumn();
            SetAlgorithm(_settings.DefaultAlgo);
            ToggleShowFullPaths(false);
        }
    }
}